yarnPath: ".yarn/releases/yarn-berry.js"
nodeLinker: 'pnp'
pnpMode: loose
packageExtensions:
  '@umijs/preset-built-in@*':
    peerDependenciesMeta:
      '@umijs/core':
        optional: true
  '@umijs/utils@*':
    peerDependenciesMeta:
      '@umijs/babel-preset-umi':
        optional: true
  '@umijs/babel-preset-umi@*':
    peerDependenciesMeta:
      '@umijs/utils':
        optional: true
